apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2                     # Number of pod replicas
  selector:
    matchLabels:
      app: nginx                           # Select pods with this label
  template:
    metadata:
      labels:
        app: nginx                         # Label for the pods
    spec:
      containers:
      - name: nginx
        image: shaikmustafa/dm                # Docker image to use
        ports:
        - containerPort: 80                # Port exposed by container
