apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80              # The port the service exposes inside the cluster
      targetPort: 80        # The port on the pod/container
      nodePort: 30080       # The port on each node to expose (range 30000-32767)
